import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";

import { Flex, Layout } from "antd";

import { Header, Content, Footer } from "antd/es/layout/layout";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png", // /public/icon.png
    shortcut: "/shortcut-icon.png",
    apple: "/apple-icon.png",
    // you can specify multiple sizes
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/apple-touch-icon-precomposed.png",
    },
  },
};

export default function AuthLayout({ children }) {
  return (
    <html lang="es-MX">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Layout style={{ minHeight: "100vh" }}>
            <Navbar />
            <Content>{children}</Content>
            <Footer className="!bg-primary !text-white text-center">
              Dica ©2025 Created by Dica
            </Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
