import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";

import { Flex, Layout, Menu, Breadcrumb, theme, Space } from "antd";

import { Header, Content, Footer } from "antd/es/layout/layout";
import Sidebar from "@/components/Sidebar";
import LogoutButton from "@/components/Logout";
import LoadingOverlay from "@/components/LoadingOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const headerStyle = {
  padding: 0,
  backgroundColor: "#4096ff",
};
const contentStyle = {
  margin: "0 16px",
  backgroundColor: "#0958d9",
};
const footerStyle = {
  textAlign: "center",
  color: "#fff",
  backgroundColor: "#4096ff",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="es-MX">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <LoadingOverlay />
          <Layout style={{ minHeight: "100vh", maxWidth: "90vw" }}>
            <Sidebar />
            <Space direction="vertical" size="large" style={{ width: "100%" }}>
              <Header
                style={{
                  backgroundColor: "white",
                  display: "flex",
                  justifyContent: "end",
                }}
              >
                <LogoutButton />
              </Header>
              <Content
                style={{
                  backgroundColor: "white",
                }}
              >
                {children}
              </Content>

              <Footer
                style={{
                  textAlign: "center",
                }}
              >
                Dica ©{new Date().getFullYear()}
              </Footer>
            </Space>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
