import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";

import { Layout, Space } from "antd";

import { Header, Content, Footer } from "antd/es/layout/layout";
import Sidebar from "@/components/Sidebar";
import LogoutButton from "@/components/Logout";
import LoadingOverlay from "@/components/LoadingOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <html lang="es-MX">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <LoadingOverlay />
          <Layout hasSider={true} style={{ maxWidth: "100%" }}>
            <Sidebar />
            <Space
              direction="vertical"
              size="large"
              style={{
                width: "100%",
                height: "100%",
                backgroundColor: "#e5e7eb",
              }}
            >
              <Header
                style={{
                  backgroundColor: "white",
                  display: "flex",
                  justifyContent: "end",
                }}
              >
                <LogoutButton />
              </Header>
              <Content>{children}</Content>

              <Footer
                style={{
                  textAlign: "center",
                }}
              >
                Dica ©{new Date().getFullYear()}
              </Footer>
            </Space>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
